# Ordered list of releases. 
helmfiles:
  - "helmfile.d/prometheus-operator.yaml"
  - "helmfile.d/cluster-autoscaler.yaml"
  - "helmfile.d/kiam.yaml"
  - "helmfile.d/external-dns.yaml"
  - "helmfile.d/kube-lego.yaml"
  - "helmfile.d/nginx-ingress.yaml"
  - "helmfile.d/kube-prometheus.yaml"
  - "helmfile.d/grafana.yaml"
  - "helmfile.d/heapster.yaml"
  - "helmfile.d/dashboard.yaml"
  - "helmfile.d/portal.yaml"
