repositories:
# Incubator repo of official helm charts
- name: "incubator"
  url: "http://storage.googleapis.com/kubernetes-charts-incubator"


releases:

################################################################################
## AWS ALB Ingress Controller ####################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/blob/master/incubator/aws-alb-ingress-controller/values.yaml
#
- name: "alb-ingress"
  namespace: "kube-system"
  labels:
    chart: "aws-alb-ingress-controller"
    repo: "incubator"
    component: "ingress"
    namespace: "kube-system"
    vendor: "kubernetes"
    default: "false"
  chart: "incubator/aws-alb-ingress-controller"
  version: "0.1.4"
  wait: true
  values:
  - clusterName: us-west-2.testing.cloudposse.co
    autoDiscoverAwsRegion: true
    autoDiscoverAwsVpcID: true
    scope:
      ## If provided, the ALB ingress controller will only act on Ingress resources annotated with this class
      ## Ref: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/configuration.md#limiting-ingress-class
      ingressClass: alb

      ## If true, the ALB ingress controller will only act on Ingress resources in a single namespace
      ## Default: false; watch all namespaces
      singleNamespace: false

      ## If scope.singleNamespace=true, the ALB ingress controller will only act on Ingress resources in this namespace
      ## Ref: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/configuration.md#limiting-namespaces
      ## Default: namespace of the ALB ingress controller
      watchNamespace: ""

    extraArgs: {}

    extraEnv: {}
    # AWS_ACCESS_KEY_ID: ""
    # AWS_SECRET_ACCESS_KEY: ""

    podAnnotations:
      iam.amazonaws.com/role: cpco-testing-alb-ingress

    podLabels: {}

    # whether configure readinessProbe on controller pod
    enableReadinessProbe: false

    # How often (in seconds) to check controller readiness
    readinessProbeInterval: 60

    # How long to wait before timeout (in seconds) when checking controller readiness
    readinessProbeTimeout: 3

    # How long to wait (in seconds) before checking the readiness probe
    readinessProbeInitialDelay: 30

    # whether configure livenessProbe on controller pod
    enableLivenessProbe: false

    # How long to wait (in seconds) before checking the liveness probe
    livenessProbeInitialDelay: 30

    rbac:
      ## If true, create & use RBAC resources
      ##
      create: true
      serviceAccountName: default

    image:
      repository: "docker.io/amazon/aws-alb-ingress-controller"
      ### Optional: AWS_ALB_INGRESS_IMAGE_TAG
      tag: '{{ env "AWS_ALB_INGRESS_IMAGE_TAG" | default "v1.1.1" }}'
      pullPolicy: Always

    replicaCount: 1

    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi

    nodeSelector: {}
    # node-role.kubernetes.io/node: "true"
    # tier: cs

    tolerations: []
    #  - key: "node-role.kubernetes.io/master"
    #    effect: NoSchedule

    affinity: {}
