repositories:
# Cloud Posse incubator repo of helm charts
- name: "cloudposse-incubator"
  url: "https://charts.cloudposse.com/incubator/"

# Cloud Flare repo of helm charts
- name: "cloudflare"
  url: "https://cloudflare.github.io/helm-charts"


releases:

################################################################################
## CloudFlare Ingress Controller ###############################################
################################################################################

#
# References:
#   - https://github.com/cloudflare/cloudflare-ingress-controller/blob/master/chart/values.yaml
#
- name: "argo"
  namespace: "kube-system"
  labels:
    chart: "cloudflare-ingress-controller"
    component: "ingress"
    namespace: "kube-system"
    vendor: "cloudflare"
    default: "false"
  chart: "cloudflare/argo-tunnel"
  version: "0.6.2"
  wait: true
  values:
    # Default values for cloudflare-argo-ingress.
    # replicaCount is used only when cloudflare loadbalancing is enabled
    - controller:
        name: controller
        image:
          repository: "gcr.io/cloudflare-registry/argo-tunnel"
          tag: "0.6.2"
          pullPolicy: "IfNotPresent"
        ingressClass: argo-tunnel
        logLevel: 4
        replicaCount: 1
        defaultOriginSecret: 'kube-system/argo-secret-monochart-files-default'
        resources:
          limits:
            cpu: '{{ env "ARGO_LIMIT_CPU" | default "100m" }}'
            memory: '{{ env "ARGO_LIMIT_MEMORY" | default "128Mi" }}'
      # Enable load balancing
      # requires load balancing enabled on the cloudflare account.
      loadbalancing:
        enabled: false

      rbac:
        create: {{ env "RBAC_ENABLED" | default "false" }}
        install: {{ env "RBAC_ENABLED" | default "false" }}
        name: '{{ env "ARGO_RBAC_ROLE_NAME" | default "" }}'

      serviceAccount:
        create: {{ env "RBAC_ENABLED" | default "false" }}
        name: '{{ env "ARGO_SERVICE_ACCOUNT_NAME" | default "" }}'


#######################################################################################
## argo-secret                                                                       ##
## Provide domain secret for argo                                                    ##
#######################################################################################
- name: "argo-secret"
  namespace: "kube-system"
  labels:
    chart: "monochart"
    component: "ingress"
    namespace: "kube-system"
    vendor: "cloudposse"
    default: "false"
  chart: "cloudposse-incubator/monochart"
  version: "0.9.0"
  wait: true
  values:
  - secrets:
      default:
        enabled: true
        ## Cloudflare account details

        # The secret contains the base64-encoded origin certificate for your cloudflare domain.
        # Set the install flag false to configure manually in the cluster later.
        #   See https://developers.cloudflare.com/argo-tunnel/quickstart/quickstart/ for information on
        # obtaining the origin certificate
        files:
          # cat /localhost/.cloudflared/cert.pem | chamber write kops ARGO_SECRET_CERTIFICATE -
          cert.pem: |-
{{ env "ARGO_SECRET_CERTIFICATE" | indent 12 }}
