repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:

################################################################################
## cluster-autoscaler ####################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/stable/cluster-autoscaler
#   - https://github.com/helm/charts/blob/master/stable/cluster-autoscaler/values.yaml
#   - https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
#
- name: "cluster-autoscaler"
  namespace: "kube-system"
  labels:
    chart: "cluster-autoscaler"
    repo: "stable"
    namespace: "kube-system"
    vendor: "kubernetes"
    default: '{{ env "KOPS_CLUSTER_AUTOSCALER_ENABLED" | default "false" }}'
  chart: "stable/cluster-autoscaler"
  version: "0.7.0"
  wait: true
  values:
    - image:
        ### Optional: CLUSTER_AUTOSCALER_IMAGE_TAG;
        tag: '{{ env "CLUSTER_AUTOSCALER_IMAGE_TAG" | default "v1.2.2" }}'
      autoDiscovery:
        ### Required: KOPS_CLUSTER_NAME; e.g. cluster.k8s.local
        clusterName: '{{ env "KOPS_CLUSTER_NAME" }}'
      cloudProvider: aws
      rbac:
        ## If true, create & use RBAC resources
        ##
        ### Optional: RBAC_ENABLED;
        create: {{ env "RBAC_ENABLED" | default "false" }}
        ## If true, create & use Pod Security Policy resources
        ## https://kubernetes.io/docs/concepts/policy/pod-security-policy/
        ### Optional: CLUSTER_AUTOSCALER_RBAC_PSP_ENABLED;
        pspEnabled: {{ env "CLUSTER_AUTOSCALER_RBAC_PSP_ENABLED" | default "false" }}
        ## Ignored if rbac.create is true
        ##
        ### Optional: CLUSTER_AUTOSCALER_RBAC_SERVICE_ACCOUNT_NAME;
        serviceAccountName: '{{ env "CLUSTER_AUTOSCALER_RBAC_SERVICE_ACCOUNT_NAME" | default "default" }}'
