repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"

releases:

################################################################################
## External DNS ################################################################
################################################################################

#
# References:
#   - https://github.com/kubernetes/charts/blob/master/stable/external-dns/values.yaml
#
- name: "dns"
  namespace: "kube-system"
  labels:
    chart: "external-dns"
    repo: "stable"
    component: "ingress"
    namespace: "kube-system"
    vendor: "kubernetes-incubator"
    default: "true"
  chart: "stable/external-dns"
  version: "0.5.4"
  wait: true
  values:
    - extraEnv:
        EXTERNAL_DNS_SOURCE: "service\ningress"
      ### Required: EXTERNAL_DNS_TXT_OWNER_ID; e.g. us-west-2.staging.cloudposse.org
      txtOwnerId: '{{ env "EXTERNAL_DNS_TXT_OWNER_ID" }}'
      ### Required: EXTERNAL_DNS_TXT_PREFIX; e.g. 11591833-F9CE-407C-8519-35A947DB1D87-
      txtPrefix: '{{ env "EXTERNAL_DNS_TXT_PREFIX" }}'
      publishInternalServices: true
      provider: "aws"
      podAnnotations:
        ### Required: EXTERNAL_DNS_IAM_ROLE; e.g. cp-staging-external-dns
        iam.amazonaws.com/role: '{{ env "EXTERNAL_DNS_IAM_ROLE" }}'
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      rbac:
        ## If true, create & use RBAC resources
        ##
        ### Optional: EXTERNAL_DNS_RBAC_ENABLED;
        create: {{ and (env "KOPS_AUTHORIZATION_RBAC_ENABLED" | default "false") (env "EXTERNAL_DNS_RBAC_ENABLED" | default "false") }}
        ## Ignored if rbac.create is true
        ##
        ### Optional: EXTERNAL_DNS_RBAC_SERVICE_ACCOUNT_NAME;
        serviceAccountName: '{{ env "EXTERNAL_DNS_RBAC_SERVICE_ACCOUNT_NAME" | default "default" }}'

