helmDefaults:
  args:
    - "--wait"
    - "--timeout=600" 
    - "--force"
    - "--reset-values"

repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"


releases:

################################################################################
## CERT-MANAGER - Automatic Let's Encrypt for Ingress  #########################
################################################################################

- name: "cert-manager"
  namespace: "kube-system"
  labels:
    chart: "cert-manager"
    component: "ingress"
    namespace: "kube-system"
    vendor: "jetstack"
    default: "false"
  chart: "stable/cert-manager"
  version: "v0.4.0"
  values:
    - rbac:
        ### Optional: CERT_MANAGER_RBAC_CREATE;
        create: {{ env "CERT_MANAGER_RBAC_CREATE" | default "true" }}
      ingressShim:
        ### Optional: CERT_MANAGER_INGRESS_SHIM_DEFAULT_ISSUER_NAME;
        defaultIssuerName: '{{ env "CERT_MANAGER_INGRESS_SHIM_DEFAULT_ISSUER_NAME" | default "letsencrypt-prod" }}'
        ### Optional: CERT_MANAGER_INGRESS_SHIM_DEFAULT_ISSUER_KIND;
        defaultIssuerKind: '{{ env "CERT_MANAGER_INGRESS_SHIM_DEFAULT_ISSUER_KIND" | default "ClusterIssuer" }}'
      tolerations:
        - key: "node-role.kubernetes.io/node"
          effect: "NoSchedule"
      serviceAccount:
        # Specifies whether a service account should be created
        ### Optional: CERT_MANAGER_SERVICE_ACCOUNT_CREATE;
        create: {{ env "CERT_MANAGER_SERVICE_ACCOUNT_CREATE" | default "true" }}
        # The name of the service account to use.
        # If not set and create is true, a name is generated using the fullname template
        ### Optional: CERT_MANAGER_SERVICE_ACCOUNT_CREATE;
        name: '{{ env "CERT_MANAGER_SERVICE_ACCOUNT_NAME" | default "" }}'
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "50m"
          memory: "128Mi"
