helmDefaults:
  args:
  - "--wait"
  - "--timeout=600"
  - "--force"
  - "--reset-values"

repositories:
# Cloud Posse incubator repo of helm charts
- name: "cloudposse-incubator"
  url: "https://charts.cloudposse.com/incubator/"

releases:

#######################################################################################
## portal                                                                            ##
## Portal for Kubernetes services                                                    ##
#######################################################################################

#
# References:
#   - https://github.com/cloudposse/charts/tree/master/incubator/portal
#   - https://github.com/cloudposse/charts/blob/master/incubator/portal/values.yaml
#
- name: "portal"
  namespace: "monitoring"
  labels:
    chart: "portal"
    component: "monitoring"
    namespace: "monitoring"
    vendor: "cloudposse"
    default: "true"
  chart: "cloudposse-incubator/portal"
  version: "0.2.0"
  values:
  - '{{ env "PORTAL_BACKENDS_VALUES_FILE" | default "values/portal.backends.yaml" }}'
  - backends:
      ### Optional: PORTAL_BACKEND_K8S_DASHBOARD_ENABLED
      {{ if eq (env "PORTAL_BACKEND_K8S_DASHBOARD_ENABLED" | default "true") "true" }}
      dashboard:
        ### Optional: PORTAL_BACKEND_K8S_DASHBOARD_NAME
        name: '{{ env "PORTAL_BACKEND_K8S_DASHBOARD_NAME" | default "Kubernetes" }}'
        ### Optional: PORTAL_BACKEND_K8S_DASHBOARD_EXTERNAL_NAME;
        externalName: '{{ env "PORTAL_BACKEND_K8S_DASHBOARD_EXTERNAL_NAME" | default "kubernetes-dashboard.kube-system" }}'
        ### Optional: PORTAL_BACKEND_K8S_DASHBOARD_SERVICE_PORT;
        servicePort: '{{ env "PORTAL_BACKEND_K8S_DASHBOARD_SERVICE_PORT" | default "443" }}'
        ### Optional: PORTAL_BACKEND_K8S_DASHBOARD_TLS;
        tls: '{{ env "PORTAL_BACKEND_K8S_DASHBOARD_TLS" | default "true" }}'
        external: false
      {{ end }}
      ### Optional: PORTAL_BACKEND_GRAFANA_ENABLED
      {{ if eq (env "PORTAL_BACKEND_GRAFANA_ENABLED" | default "true") "true" }}
      grafana:
        ### Optional: PORTAL_BACKEND_GRAFANA_NAME
        name: '{{ env "PORTAL_BACKEND_GRAFANA_NAME" | default "Grafana" }}'
        ### Optional: PORTAL_BACKEND_GRAFANA_EXTERNAL_NAME;
        externalName: '{{ env "PORTAL_BACKEND_GRAFANA_EXTERNAL_NAME" | default "kube-prometheus-grafana.monitoring" }}'
        ### Optional: PORTAL_BACKEND_GRAFANA_SERVICE_PORT;
        servicePort: '{{ env "PORTAL_BACKEND_GRAFANA_SERVICE_PORT" | default "80" }}'
        ### Optional: PORTAL_BACKEND_GRAFANA_TLS;
        tls: '{{ env "PORTAL_BACKEND_GRAFANA_TLS" | default "false" }}'
        external: false
      {{ end }}
      ### Optional: PORTAL_BACKEND_ALERTS_ENABLED
      {{ if eq (env "PORTAL_BACKEND_ALERTS_ENABLED" | default "true") "true" }}
      {{ env "KUBE_PROMETHEUS_ALERT_MANAGER_SUBHOST" | default "alerts" }}:
        ### Optional: PORTAL_BACKEND_ALERTS_NAME
        name: '{{ env "PORTAL_BACKEND_ALERTS_NAME" | default "Alerts" }}'
        ### Optional: PORTAL_BACKEND_ALERTS_EXTERNAL_NAME;
        externalName: '{{ env "PORTAL_BACKEND_ALERTS_EXTERNAL_NAME" | default "kube-prometheus-alertmanager.monitoring" }}'
        ### Optional: PORTAL_BACKEND_ALERTS_SERVICE_PORT;
        servicePort: '{{ env "PORTAL_BACKEND_ALERTS_SERVICE_PORT" | default "9093" }}'
        ### Optional: PORTAL_BACKEND_ALERTS_TLS;
        tls: '{{ env "PORTAL_BACKEND_ALERTS_TLS" | default "false" }}'
        external: false
      {{ end }}
      ### Optional: PORTAL_BACKEND_PROMETHEUS_ENABLED
      {{ if eq (env "PORTAL_BACKEND_PROMETHEUS_ENABLED" | default "true") "true" }}
      {{ env "KUBE_PROMETHEUS_SUBHOST" | default "prometheus" }}:
        ### Optional: PORTAL_BACKEND_PROMETHEUS_NAME
        name: '{{ env "PORTAL_BACKEND_PROMETHEUS_NAME" | default "Prometheus" }}'
        ### Optional: PORTAL_BACKEND_PROMETHEUS_EXTERNAL_NAME;
        externalName: '{{ env "PORTAL_BACKEND_PROMETHEUS_EXTERNAL_NAME" | default "kube-prometheus.monitoring" }}'
        ### Optional: PORTAL_BACKEND_PROMETHEUS_SERVICE_PORT;
        servicePort: '{{ env "PORTAL_BACKEND_PROMETHEUS_SERVICE_PORT" | default "9090" }}'
        ### Optional: PORTAL_BACKEND_PROMETHEUS_TLS;
        tls: '{{ env "PORTAL_BACKEND_PROMETHEUS_TLS" | default "false" }}'
        external: false
      {{ end }}
      ### Optional: PORTAL_BACKEND_DOCS_ENABLED
      {{ if eq (env "PORTAL_BACKEND_DOCS_ENABLED" | default "true") "true" }}
      docs:
        ### Optional: PORTAL_BACKEND_DOCS_NAME
        name: '{{ env "PORTAL_BACKEND_DOCS_NAME" | default "Docs" }}'
        ### Optional: PORTAL_BACKEND_DOCS_ENDPOINT
        endpoint: '{{ env "PORTAL_BACKEND_DOCS_ENDPOINT" | default "https://docs.cloudposse.com/" }}'
        external: true
      {{ end }}
      ### Optional: PORTAL_BACKEND_KIBANA_ENABLED
      {{ if eq (env "PORTAL_BACKEND_KIBANA_ENABLED" | default "false") "true" }}
      kibana:
        ### Optional: PORTAL_BACKEND_KIBANA_NAME
        name: '{{ env "PORTAL_BACKEND_KIBANA_NAME" | default "Kibana" }}'
        ### Optional: PORTAL_BACKEND_KIBANA_EXTERNAL_NAME;
        externalName: '{{ env "PORTAL_BACKEND_KIBANA_EXTERNAL_NAME" | default "kibana.monitoring" }}'
        ### Optional: PORTAL_BACKEND_KIBANA_SERVICE_PORT;
        servicePort: '{{ env "PORTAL_BACKEND_KIBANA_SERVICE_PORT" | default "80" }}'
        ### Optional: PORTAL_BACKEND_KIBANA_TLS;
        tls: '{{ env "PORTAL_BACKEND_KIBANA_TLS" | default "false" }}'
        external: false
      {{ end }}
  - config:
      ### Required: PORTAL_TITLE
      title: '{{ env "PORTAL_TITLE" }}'
      ### Required: PORTAL_BRAND
      brand: '{{ env "PORTAL_BRAND" }}'
      ### Required: PORTAL_HOSTNAME
      basehost: '{{ env "PORTAL_HOSTNAME" }}'
      image:
        ### Optional: PORTAL_BRAND_IMAGE_FAVICON_URL
        favicon: '{{ env "PORTAL_BRAND_IMAGE_FAVICON_URL" | default "https://cloudposse.com/wp-content/uploads/sites/29/2016/04/favicon-152.png" }}'
        ### Optional: PORTAL_BRAND_IMAGE_URL
        url: '{{ env "PORTAL_BRAND_IMAGE_URL" | default "https://raw.githubusercontent.com/cloudposse/helm-chart-scaffolding/master/logo.png" }}'
        ### Optional: PORTAL_BRAND_IMAGE_WIDTH
        width: '{{ env "PORTAL_BRAND_IMAGE_WIDTH" | default "35" }}'
    dashboard:
      ### Optional: PORTAL_DASHBOARD_REPLICA_COUNT
      replicaCount: '{{ env "PORTAL_DASHBOARD_REPLICA_COUNT" | default "2" }}'
      image:
        repository: "nginx"
        ### Optional: PORTAL_DASHBOARD_IMAGE_TAG
        tag: '{{ env "PORTAL_DASHBOARD_IMAGE_TAG" | default "latest" }}'
        pullPolicy: "Always"
      service:
        externalPort: "80"
        internalPort: "80"
      resources:
        limits:
          cpu: "5m"
          memory: "16Mi"
        requests:
          cpu: "3m"
          memory: "8Mi"
    proxy:
      enabled: true
      ### Optional: PORTAL_PROXY_REPLICA_COUNT
      replicaCount: '{{ env "PORTAL_PROXY_REPLICA_COUNT" | default "2" }}'
      image:
        repository: "traefik"
        ### Optional: PORTAL_PROXY_IMAGE_TAG
        tag: '{{ env "PORTAL_PROXY_IMAGE_TAG" | default "1.5.4" }}'
        pullPolicy: "Always"
      service:
        externalPort: "80"
        internalPort: "80"
      resources:
        limits:
          cpu: "5m"
          memory: "64Mi"
        requests:
          cpu: "3m"
          memory: "32Mi"
    oauth2-proxy:
      app:
        useSSL: false
        upstreams:
        - "file:///dev/null"
        provider: "github"
        ### Required: PORTAL_OAUTH2_PROXY_GITHUB_CLIENT_ID
        clientID: '{{ env "PORTAL_OAUTH2_PROXY_GITHUB_CLIENT_ID" }}'
        ### Required: PORTAL_OAUTH2_PROXY_GITHUB_CLIENT_SECRET
        clientSecret: '{{ env "PORTAL_OAUTH2_PROXY_GITHUB_CLIENT_SECRET" }}'
        ### Required: PORTAL_OAUTH2_PROXY_GITHUB_ORGANIZATION
        githubOrg: '{{ env "PORTAL_OAUTH2_PROXY_GITHUB_ORGANIZATION" }}'
        ### Required: PORTAL_OAUTH2_PROXY_GITHUB_TEAM
        githubTeam: '{{ env "PORTAL_OAUTH2_PROXY_GITHUB_TEAM" }}'
        requestLogging: false
        passAccessToken: false
        passBasicAuth: false
        passHostHeader: true
        ### Required: PORTAL_OAUTH2_PROXY_COOKIE_NAME
        cookieName: '{{ env "PORTAL_OAUTH2_PROXY_COOKIE_NAME" }}'
        ### Required: PORTAL_OAUTH2_PROXY_COOKIE_SECRET
        cookieSecret: '{{ env "PORTAL_OAUTH2_PROXY_COOKIE_SECRET" }}'
        ### Required: PORTAL_HOSTNAME
        cookieDomain: '{{ env "PORTAL_HOSTNAME" }}'
        cookieSecure: true
        cookieHttponly: false
        ### Optional: PORTAL_OAUTH2_PROXY_REPLICA_COUNT
        replicaCount: '{{ env "PORTAL_OAUTH2_PROXY_REPLICA_COUNT" | default "2" }}'
        image:
          repository: "cloudposse/oauth2-proxy"
          ### Optional: PORTAL_OAUTH2_PROXY_IMAGE_TAG
          tag: '{{ env "PORTAL_OAUTH2_PROXY_IMAGE_TAG" | default "2.2" }}'
          pullPolicy: "Always"
        resources:
          limits:
            cpu: "10m"
            memory: "16Mi"
          requests:
            cpu: "5m"
            memory: "8Mi"
    ingress:
      enabled: true
      dns:
        enabled: false
      tls:
        ### Optional: PORTAL_INGRESS_TLS_ENABLED; e.g. false
        enabled: '{{ env "PORTAL_INGRESS_TLS_ENABLED" | default "true" }}'
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/tls-acme: "true"
        ### Required: PORTAL_INGRESS; e.g. ingress.us-west-2.staging.cloudposse.org
        external-dns.alpha.kubernetes.io/target: '{{ env "PORTAL_INGRESS" }}'
        # DNS TTL for PORTAL_HOSTNAME; e.g. 60
        external-dns.alpha.kubernetes.io/ttl: "60"
