repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com"


releases:

################################################################################
## CERT-MANAGER - Automatic Let's Encrypt for Ingress  #########################
################################################################################

#
# References:
#   - https://github.com/helm/charts/blob/master/stable/cert-manager/values.yaml
#
- name: "cert-manager"
  namespace: "kube-system"
  labels:
    chart: "cert-manager"
    repo: "stable"
    component: "ingress"
    namespace: "kube-system"
    vendor: "jetstack"
    default: "false"
  chart: "stable/cert-manager"
  version: "v0.4.0"
  wait: true
  values:
    - rbac:
        ### Optional: RBAC_ENABLED;
        create: {{ env "RBAC_ENABLED" | default "false" }}
      ingressShim:
        ### Optional: CERT_MANAGER_INGRESS_SHIM_DEFAULT_ISSUER_NAME;
        defaultIssuerName: '{{ env "CERT_MANAGER_INGRESS_SHIM_DEFAULT_ISSUER_NAME" | default "letsencrypt-prod" }}'
        ### Optional: CERT_MANAGER_INGRESS_SHIM_DEFAULT_ISSUER_KIND;
        defaultIssuerKind: '{{ env "CERT_MANAGER_INGRESS_SHIM_DEFAULT_ISSUER_KIND" | default "ClusterIssuer" }}'
      tolerations:
        - key: "node-role.kubernetes.io/node"
          effect: "NoSchedule"
      serviceAccount:
        ### Optional: RBAC_ENABLED;
        create: {{ env "RBAC_ENABLED" | default "false" }}
        ### Optional: CERT_MANAGER_SERVICE_ACCOUNT_NAME;
        name: '{{ env "CERT_MANAGER_SERVICE_ACCOUNT_NAME" | default "" }}'
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "50m"
          memory: "128Mi"
